import React, { useState } from 'react';
import DashboardLayout from '../../components/DashboardLayout.jsx';
import { useDataStore } from '../../hooks/useDataStore.js';
import { useAuth } from '../../context/AuthContext.jsx';
import { motion } from 'framer-motion';
import toast from 'react-hot-toast';
import {
    Calendar, ClipboardList, Activity, Clock, CheckCircle,
    Plus, X, Loader2, Download, Pill, Utensils, ChevronRight,
    AlertCircle, User
} from 'lucide-react';

export default function PatientDashboard() {
    const [activeTab, setActiveTab] = useState('overview');
    const { user } = useAuth();
    const { appointments, prescriptions, therapies, DOCTORS, addAppointment, reload } = useDataStore();

    const myAppts = appointments.filter(a => a.patient_id === user?.id);
    const myRxs = prescriptions.filter(p => p.patient_id === user?.id);
    const myTherapies = therapies.filter(t => t.patient_id === user?.id);

    const [showBooking, setShowBooking] = useState(false);
    const [booking, setBooking] = useState({ doctor_id: '', date: '', time: '', reason: '' });
    const [bookingLoading, setBookingLoading] = useState(false);

    const TIME_SLOTS = ['09:00 AM', '09:30 AM', '10:00 AM', '10:30 AM', '11:00 AM', '11:30 AM', '02:00 PM', '02:30 PM', '03:00 PM', '03:30 PM', '04:00 PM'];

    const submitBooking = async () => {
        if (!booking.doctor_id || !booking.date || !booking.time || !booking.reason) {
            toast.error('Please fill all fields'); return;
        }
        setBookingLoading(true);
        try {
            const doctor = DOCTORS.find(d => d.id === booking.doctor_id);
            // ✅ FIX: await so data is confirmed saved to Supabase
            await addAppointment({
                patient_id: user.id,
                patient_name: user.name,
                doctor_id: booking.doctor_id,
                doctor_name: doctor?.name || 'Dr. Unknown',
                date: booking.date,
                time: booking.time,
                reason: booking.reason,
                status: 'scheduled',
            });
            toast.success('✅ Appointment booked & saved to Supabase!');
            setBooking({ doctor_id: '', date: '', time: '', reason: '' });
            setShowBooking(false);
        } catch (err) {
            toast.error('Booking failed. Please try again.');
        } finally {
            setBookingLoading(false);
        }
    };

    const downloadPrescription = (rx) => {
        const content = `
PANCHAKARMA PATIENT MANAGEMENT SYSTEM
=== DIGITAL PRESCRIPTION ===
==============================
Patient: ${rx.patient_name}
Doctor: ${rx.doctor_name}
Date: ${rx.date}
Dosha: ${rx.dosha} (${rx.dosha_confidence}% confidence)

SYMPTOMS:
${rx.symptoms}

DIAGNOSIS:
${rx.diagnosis}

MEDICINES:
${rx.medicines?.map(m => `• ${m.name} — ${m.dose}, ${m.frequency}, ${m.duration}`).join('\n') || 'None'}

THERAPY:
${rx.therapy}
Therapist: ${rx.therapist_name || 'TBD'}

DIET ADVICE:
${rx.diet}

==============================
This prescription is digitally generated by Panchakarma PMS.
    `.trim();
        const blob = new Blob([content], { type: 'text/plain' });
        const a = document.createElement('a'); a.href = URL.createObjectURL(blob);
        a.download = `My_Prescription_${rx.date}.txt`;
        a.click();
        toast.success('Prescription downloaded!');
    };

    const upcomingAppt = myAppts.find(a => a.status === 'scheduled');
    const activeTherapy = myTherapies.find(t => t.status === 'in-progress');

    return (
        <DashboardLayout activeTab={activeTab} onTabChange={setActiveTab} onRefresh={reload}>

            {/* ── OVERVIEW ── */}
            {activeTab === 'overview' && (
                <div className="space-y-6">
                    {/* Welcome Banner */}
                    <div className="rounded-2xl bg-gradient-to-r from-blue-600 to-green-600 p-6 text-white">
                        <p className="text-white/70 text-sm mb-1">Welcome back,</p>
                        <h2 className="text-2xl font-extrabold mb-3">{user?.name} 👋</h2>
                        <div className="flex flex-col sm:flex-row gap-3">
                            {upcomingAppt ? (
                                <div className="bg-white/15 border border-white/20 rounded-xl p-3 flex-1">
                                    <p className="text-white/70 text-xs mb-1">Next Appointment</p>
                                    <p className="font-bold">{upcomingAppt.date} · {upcomingAppt.time}</p>
                                    <p className="text-white/80 text-sm">{upcomingAppt.doctor_name}</p>
                                </div>
                            ) : (
                                <div className="bg-white/15 border border-white/20 rounded-xl p-3 flex-1">
                                    <p className="text-white/70 text-xs mb-1">No upcoming appointments</p>
                                    <button onClick={() => setShowBooking(true)} className="text-amber-300 font-semibold text-sm">
                                        Book one now →
                                    </button>
                                </div>
                            )}
                            {activeTherapy && (
                                <div className="bg-white/15 border border-white/20 rounded-xl p-3 flex-1">
                                    <p className="text-white/70 text-xs mb-1">Active Therapy</p>
                                    <p className="font-bold">{activeTherapy.therapy_type}</p>
                                    <p className="text-white/80 text-sm">{activeTherapy.completed_sessions}/{activeTherapy.total_sessions} sessions done</p>
                                </div>
                            )}
                        </div>
                    </div>

                    {/* Stats */}
                    <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">
                        {[
                            { label: 'Appointments', value: myAppts.length, icon: Calendar, color: 'bg-blue-50 text-blue-600' },
                            { label: 'Prescriptions', value: myRxs.length, icon: ClipboardList, color: 'bg-green-50 text-green-600' },
                            { label: 'Therapy Sessions', value: myTherapies.reduce((s, t) => s + t.completed_sessions, 0), icon: Activity, color: 'bg-purple-50 text-purple-600' },
                            { label: 'Completed', value: myAppts.filter(a => a.status === 'completed').length, icon: CheckCircle, color: 'bg-amber-50 text-amber-600' },
                        ].map((s, i) => (
                            <motion.div key={s.label} initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: i * 0.1 }}
                                className="stat-card">
                                <div className={`w-10 h-10 rounded-xl ${s.color} flex items-center justify-center mb-3`}>
                                    <s.icon className="w-5 h-5" />
                                </div>
                                <p className="text-2xl font-extrabold text-gray-900">{s.value}</p>
                                <p className="text-gray-500 text-sm mt-1">{s.label}</p>
                            </motion.div>
                        ))}
                    </div>

                    <div className="flex justify-center">
                        <button onClick={() => setShowBooking(true)}
                            className="btn-primary flex items-center gap-2">
                            <Plus className="w-4 h-4" /> Book New Appointment
                        </button>
                    </div>
                </div>
            )}

            {/* ── MY APPOINTMENTS ── */}
            {activeTab === 'appointments' && (
                <div className="space-y-4">
                    <div className="flex justify-end">
                        <button onClick={() => setShowBooking(true)} className="btn-primary flex items-center gap-2 text-sm py-2 px-4">
                            <Plus className="w-4 h-4" /> Book Appointment
                        </button>
                    </div>
                    {myAppts.length === 0 && (
                        <div className="card text-center py-12 text-gray-400">
                            <Calendar className="w-12 h-12 mx-auto mb-3 opacity-30" />
                            <p>No appointments yet</p>
                            <button onClick={() => setShowBooking(true)} className="text-blue-600 font-medium text-sm mt-2 hover:text-blue-800">
                                Book your first appointment →
                            </button>
                        </div>
                    )}
                    <div className="space-y-3">
                        {myAppts.map((a) => (
                            <motion.div key={a.id} initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} className="card">
                                <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3">
                                    <div className="flex items-center gap-4">
                                        <div className="w-12 h-12 rounded-xl bg-blue-100 text-blue-700 flex items-center justify-center font-bold text-sm">
                                            {a.doctor_name?.split(' ').map(n => n[0]).join('')}
                                        </div>
                                        <div>
                                            <p className="font-bold text-gray-900">{a.doctor_name}</p>
                                            <p className="text-gray-400 text-sm">{a.date} · {a.time}</p>
                                            <p className="text-gray-500 text-xs mt-1">Reason: {a.reason}</p>
                                        </div>
                                    </div>
                                    <span className={`status-${a.status} self-start sm:self-center`}>{a.status}</span>
                                </div>
                            </motion.div>
                        ))}
                    </div>
                </div>
            )}

            {/* ── MY PRESCRIPTIONS ── */}
            {activeTab === 'prescriptions' && (
                <div className="space-y-4">
                    {myRxs.length === 0 && (
                        <div className="card text-center py-12 text-gray-400">
                            <ClipboardList className="w-12 h-12 mx-auto mb-3 opacity-30" />
                            <p>No prescriptions yet. Book an appointment to get started.</p>
                        </div>
                    )}
                    {myRxs.map((rx) => (
                        <motion.div key={rx.id} initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} className="card">
                            <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 mb-4">
                                <div>
                                    <h3 className="font-bold text-gray-900">{rx.diagnosis}</h3>
                                    <p className="text-gray-400 text-sm">by {rx.doctor_name} · {rx.date}</p>
                                </div>
                                <div className="flex gap-2">
                                    <span className="badge bg-blue-100 text-blue-700">{rx.dosha} ({rx.dosha_confidence}%)</span>
                                    <button onClick={() => downloadPrescription(rx)}
                                        className="flex items-center gap-1 text-xs text-blue-600 bg-blue-50 hover:bg-blue-100 px-3 py-1.5 rounded-lg font-semibold transition-colors">
                                        <Download className="w-3 h-3" /> Download
                                    </button>
                                </div>
                            </div>

                            <div className="grid sm:grid-cols-2 gap-4 text-sm mb-4">
                                <div>
                                    <p className="font-semibold text-gray-700 mb-1 flex items-center gap-1">
                                        <Pill className="w-4 h-4" /> Medicines
                                    </p>
                                    <div className="space-y-1">
                                        {rx.medicines?.map((m, i) => (
                                            <div key={i} className="bg-blue-50 rounded-lg px-3 py-1.5 text-xs">
                                                <span className="font-semibold text-blue-800">{m.name}</span>
                                                <span className="text-blue-500"> · {m.dose} · {m.frequency}</span>
                                                <span className="text-blue-400"> for {m.duration}</span>
                                            </div>
                                        ))}
                                    </div>
                                </div>
                                <div>
                                    <p className="font-semibold text-gray-700 mb-1 flex items-center gap-1">
                                        <Utensils className="w-4 h-4" /> Diet Advice
                                    </p>
                                    <p className="text-gray-500 text-xs leading-relaxed">{rx.diet}</p>
                                </div>
                            </div>

                            <div className="bg-green-50 rounded-xl p-3 text-sm">
                                <p className="font-semibold text-green-700">Therapy Prescribed</p>
                                <p className="text-green-600 mt-1">{rx.therapy}</p>
                                {rx.therapist_name && <p className="text-green-500 text-xs mt-1">Therapist: {rx.therapist_name}</p>}
                            </div>
                        </motion.div>
                    ))}
                </div>
            )}

            {/* ── THERAPY PROGRESS ── */}
            {activeTab === 'therapy' && (
                <div className="space-y-4">
                    {myTherapies.length === 0 && (
                        <div className="card text-center py-12 text-gray-400">
                            <Activity className="w-12 h-12 mx-auto mb-3 opacity-30" />
                            <p>No therapy assigned yet</p>
                        </div>
                    )}
                    {myTherapies.map((t) => {
                        const pct = Math.round((t.completed_sessions / t.total_sessions) * 100);
                        return (
                            <motion.div key={t.id} initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} className="card">
                                <div className="flex items-start justify-between mb-4">
                                    <div>
                                        <h3 className="font-bold text-gray-900 text-lg">{t.therapy_type}</h3>
                                        <p className="text-gray-400 text-sm">Therapist: {t.therapist_name}</p>
                                    </div>
                                    <span className={`status-${t.status}`}>{t.status.replace('-', ' ')}</span>
                                </div>

                                {/* Progress bar */}
                                <div className="mb-4">
                                    <div className="flex justify-between text-sm text-gray-600 mb-2">
                                        <span>Overall Progress</span>
                                        <span className="font-bold">{pct}% ({t.completed_sessions}/{t.total_sessions} sessions)</span>
                                    </div>
                                    <div className="bg-gray-100 rounded-full h-4 overflow-hidden">
                                        <motion.div
                                            initial={{ width: 0 }}
                                            animate={{ width: pct + '%' }}
                                            transition={{ duration: 1, ease: 'easeOut' }}
                                            className={`h-4 rounded-full flex items-center justify-end pr-2 ${pct === 100 ? 'bg-green-500' : 'bg-blue-500'}`}
                                        >
                                            {pct > 15 && <span className="text-white text-xs font-bold">{pct}%</span>}
                                        </motion.div>
                                    </div>
                                </div>

                                {/* Timeline info */}
                                <div className="grid grid-cols-2 gap-4 text-sm mb-4">
                                    <div>
                                        <p className="text-gray-400 text-xs">Start Date</p>
                                        <p className="font-semibold text-gray-700">{t.start_date}</p>
                                    </div>
                                    <div>
                                        <p className="text-gray-400 text-xs">End Date</p>
                                        <p className="font-semibold text-gray-700">{t.end_date}</p>
                                    </div>
                                </div>

                                {/* Session notes */}
                                {t.notes && t.notes.length > 0 && (
                                    <div>
                                        <p className="font-semibold text-gray-700 text-sm mb-2">Session Notes from Therapist</p>
                                        <div className="space-y-2 max-h-48 overflow-y-auto">
                                            {t.notes.slice().reverse().map((n, i) => (
                                                <div key={i} className="bg-gray-50 rounded-xl p-3">
                                                    <div className="flex items-center justify-between mb-1">
                                                        <span className="text-xs font-bold text-gray-500">Session {n.session}</span>
                                                        <div className="flex items-center gap-2">
                                                            <span className={`text-xs font-semibold capitalize ${n.mood === 'excellent' ? 'text-green-600' : n.mood === 'good' ? 'text-blue-600' : 'text-amber-600'}`}>
                                                                {n.mood}
                                                            </span>
                                                            <span className="text-gray-400 text-xs">{n.date}</span>
                                                        </div>
                                                    </div>
                                                    <p className="text-gray-600 text-sm">{n.note}</p>
                                                </div>
                                            ))}
                                        </div>
                                    </div>
                                )}
                            </motion.div>
                        );
                    })}
                </div>
            )}

            {/* ── BOOK APPOINTMENT MODAL ── */}
            {showBooking && (
                <div className="fixed inset-0 bg-black/50 z-50 flex items-center justify-center p-4">
                    <motion.div initial={{ opacity: 0, scale: 0.95 }} animate={{ opacity: 1, scale: 1 }}
                        className="bg-white rounded-2xl p-6 w-full max-w-md shadow-2xl">
                        <div className="flex items-center justify-between mb-5">
                            <div>
                                <h2 className="text-lg font-bold text-gray-900">Book Appointment</h2>
                                <p className="text-gray-400 text-xs">Schedule a consultation with a doctor</p>
                            </div>
                            <button onClick={() => setShowBooking(false)} className="p-2 hover:bg-gray-100 rounded-xl"><X className="w-4 h-4" /></button>
                        </div>

                        <div className="space-y-4">
                            <div>
                                <label className="label">Select Doctor</label>
                                <select className="input-field" value={booking.doctor_id} onChange={e => setBooking({ ...booking, doctor_id: e.target.value })}>
                                    <option value="">Choose a doctor...</option>
                                    {DOCTORS.map(d => <option key={d.id} value={d.id}>{d.name} — {d.specialization}</option>)}
                                </select>
                            </div>
                            <div>
                                <label className="label">Preferred Date</label>
                                <input type="date" className="input-field" value={booking.date}
                                    min={new Date().toISOString().split('T')[0]}
                                    onChange={e => setBooking({ ...booking, date: e.target.value })} />
                            </div>
                            <div>
                                <label className="label">Time Slot</label>
                                <div className="grid grid-cols-3 gap-2">
                                    {TIME_SLOTS.map(slot => (
                                        <button key={slot} type="button" onClick={() => setBooking({ ...booking, time: slot })}
                                            className={`py-2 rounded-xl text-xs font-semibold border transition-all ${booking.time === slot ? 'bg-blue-600 text-white border-blue-600' : 'border-gray-200 text-gray-600 hover:border-blue-300'}`}>
                                            {slot}
                                        </button>
                                    ))}
                                </div>
                            </div>
                            <div>
                                <label className="label">Reason for Visit</label>
                                <textarea className="input-field min-h-[70px] resize-none" value={booking.reason}
                                    onChange={e => setBooking({ ...booking, reason: e.target.value })}
                                    placeholder="Describe your symptoms or reason for consultation..." />
                            </div>
                        </div>

                        <div className="flex gap-3 mt-5">
                            <button onClick={() => setShowBooking(false)} className="flex-1 btn-ghost">Cancel</button>
                            <button onClick={submitBooking} disabled={bookingLoading}
                                className="flex-1 btn-primary flex items-center justify-center gap-2">
                                {bookingLoading ? <Loader2 className="w-4 h-4 animate-spin" /> : <Calendar className="w-4 h-4" />}
                                {bookingLoading ? 'Booking...' : 'Confirm Booking'}
                            </button>
                        </div>
                    </motion.div>
                </div>
            )}
        </DashboardLayout>
    );
}
